@FetchProx_HostAddress = http://localhost:8080

POST {{FetchProx_HostAddress}}/fetch
Content-type: text/plain

https://en.wikipedia.org/wiki/Proxy_server

###

GET {{FetchProx_HostAddress}}/fetch?url=https://en.wikipedia.org/wiki/Proxy_server
Access-Control-Request-Method: GET

###